otaAndIg:
  VCU_VehicleCtrlMod0: 
    cycleTime: 100
    sendId: 0x18FF0227
    sendLength: 8
    sendValue: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

  VCU_VehicleCtrlMod1: 
    cycleTime: 100
    sendId: 0x18FF0227
    sendLength: 8
    sendValue: [0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00]
  
  BCM_PowerState0: 
    cycleTime: 100
    sendId: 0x18FF0121
    sendLength: 8
    sendValue: [0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

  BCM_PowerState1: 
    cycleTime: 100
    sendId: 0x18FF0121
    sendLength: 8
    sendValue: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
