filterMsg:
  1: 
    sourceCan: can2
    desCan: can1
    filterId: 
      - 0x10FB01D8
      - 0x10FB03D8
      - 0x10FB0FD8

  2: 
    sourceCan: can1
    desCan: can2

cycleMsg:
  VCU_VehicleSpeed: 
    desCan: can1
    cycleTime: 100
    sendId: 0x10FB0CD8
    sendLength: 8
    sendValue: [0x04, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x00]

  VCU_VehicleSpdVId:
    desCan: can1
    cycleTime: 100
    sendId: 0x10FB03D8
    sendLength: 8
    sendValue: [0x04, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x00]

ota:
  sourceCan: can1
  id: 0x18FF4D4A 
  status1: 02
  status2: 00

url: "192.168.99.9:8080/ota"

listen: 
  sourceCan: can2
  id: 0x10FB04D8


  
