cycleMsg:
  VCU_VehicleSpeed: 
    cycleTime: 100
    sendId: 0x18FEF100
    sendLength: 8
    sendValue: [0x04, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x00]

  TCU_CurrentGear: 
    cycleTime: 100
    sendId: 0x18F101D0
    sendLength: 8
    sendValue: [0x60, 0x05, 0x01, 0x51, 0x00, 0x00, 0x00, 0x01]

  BMS_ChrgGunSt: 
    cycleTime: 200
    sendId: 0x18F804F4
    sendLength: 8
    sendValue: [0x88, 0xF3, 0x01, 0xFF, 0x02, 0x23, 0x24, 0x01]
  
  BMS_BatterySOC: 
    cycleTime: 100
    sendId: 0x18F802F4
    sendLength: 8
    sendValue: [0x0A, 0xC8, 0x06, 0x42, 0x27, 0x96, 0xC0, 0x8C]

  VCU_VehicleSpdVId: 
    cycleTime: 100
    sendId: 0x18FF0727
    sendLength: 8
    sendValue: [0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

otaAndIg:
  VCU_VehicleCtrlMod0: 
    cycleTime: 100
    sendId: 0x18FF0227
    sendLength: 8
    sendValue: [0x88, 0x10, 0x09, 0x00, 0x01, 0x00, 0x01, 0x01]

  VCU_VehicleCtrlMod1: 
    cycleTime: 100
    sendId: 0x18FF0227
    sendLength: 8
    sendValue: [0x88, 0x10, 0x09, 0x10, 0x01, 0x00, 0x01, 0x01]
  
  BCM_PowerState0: 
    cycleTime: 100
    sendId: 0x18FF0121
    sendLength: 8
    sendValue: [0xD0, 0x28, 0xCD, 0xA5, 0x6D, 0x66, 0x25, 0x50]

  BCM_PowerState1: 
    cycleTime: 100
    sendId: 0x18FF0121
    sendLength: 8
    sendValue: [0xD2, 0x28, 0xCD, 0xA5, 0x6D, 0x66, 0x25, 0x50]
